version: "2"
services:
  master:
    image: lhoussou/jenkins-master:v1
    ports:
      - "8443:8443"
    environment:
      - JAVA_OPTS=-Xmx2048m
      - JENKINS_OPTS=--httpPort=8080 --httpsPort=8443 --httpsKeyStore=${httpsKeyStore} --httpsKeyStorePassword=${httpsKeyStorePassword}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER_BIN}:/usr/bin/docker
      - jenkins-master:/var/jenkins_home
      - /etc/keystore.jks:/etc/keystore.jks

  worker:
    image: lhoussou/jenkins-slave:v1
    environment:
      JAVA_OPTS: "-Xmx2048m"
      JENKINS_MASTER: "http://master:8080"
      JENKINS_NAME: "worker"
      JENKINS_USER: "jenkins"
      JENKINS_PASS: "jenkins"
      JENKINS_RETRY: "10"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER_BIN}:/usr/bin/docker
      - jenkins-worker:/var/jenkins_home/worker
    depends_on:
      - master

volumes:
  jenkins-master:
  jenkins-worker:
